/**
 * Adventures with Babe - Arseniy's 32nd Birthday Edition
 * Comprehensive curated dataset of 42 adventures across San Francisco and the Bay Area (<2 hrs drive).
 * Features all 7 spreadsheet activities, 12 Instagram inspirations, custom dietary notes, and family tips for Naomi.
 */

const ADVENTURES_DATA = [
  // --- INCLUSIONS FROM SPREADSHEET ---
  {
    id: "salesforce-park-rooftop",
    title: "Salesforce Park Rooftop Garden & Living Canopy",
    image: "https://images.unsplash.com/photo-1577705998148-6da4f3963bc8?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: true,
    neighborhood: "Transbay / Downtown SF",
    address: "425 Mission St, San Francisco, CA 94105",
    lat: 37.7897,
    lng: -122.3969,
    driveTime: "Local SF",
    duration: "1 - 1.5 hours",
    bestTime: "Late afternoon / Sunset golden hour when city towers illuminate",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi will love the interactive water fountain (fountain jets dance to passing buses below!), children's play area, and outdoor book cart.",
    arseniyHighlights: "Stunning 360-degree urban canyon views surrounded by SF skyscrapers; peaceful 0.6-mile perimeter walking loop suspended 70 feet in the air.",
    arseniyFoodPick: "Hit Barebottle Brewing on the rooftop lawn for a fresh Double IPA or fruited kettle sour, followed by a velvety double-shot cortado at Andytown Coffee Roasters downstairs.",
    joannaVeggiePick: "Grab fresh vegetarian matcha lattes, avocado toast flights, or oat milk treats at the rooftop cafe kiosk.",
    instagramHandle: "@secret_sanfrancisco",
    instagramUrl: "https://www.instagram.com/secret_sanfrancisco/",
    tags: ["Rooftop Garden", "Sunset Views", "Naomi Approved", "Urban Walk"],
    description: "A lush 5.4-acre public park floating four stories above the bustling downtown streets. Wander through 13 botanical garden ecosystems featuring towering Chilean wine palms, Australian tree ferns, a Redwood grove, and sweeping city skyline views.",
    tips: "Free admission! Take the glass gondola from Salesforce Plaza directly to the roof for the ultimate entrance."
  },
  {
    id: "salesforce-park-gondola",
    title: "Salesforce Park Gondola Experience",
    image: "https://images.unsplash.com/photo-1506146332389-18140dc7b2fb?w=800&auto=format&fit=crop&q=80",
    category: "unique",
    spreadsheetItem: true,
    neighborhood: "Financial District / SOMA, SF",
    address: "Salesforce Plaza, Mission & Fremont St, San Francisco, CA 94105",
    lat: 37.7903,
    lng: -122.3975,
    driveTime: "Local SF",
    duration: "30 minutes",
    bestTime: "Sunset or twilight as office towers glow",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi will feel like she's riding an alpine aerial tram right into the clouds in the middle of the city!",
    arseniyHighlights: "Quick, thrilling vertical climb with floor-to-ceiling glass offering cool mechanical engineering views of the plaza.",
    arseniyFoodPick: "Stop by Mourad or The Morris nearby for wood-grilled lamb chops, house-smoked meats, and artisanal smoky mezcal cocktails.",
    joannaVeggiePick: "Head straight up to the rooftop garden for botanical lavender tea or fresh juice.",
    instagramHandle: "@secret_sanfrancisco",
    instagramUrl: "https://www.instagram.com/secret_sanfrancisco/",
    tags: ["Gondola", "Only in SF", "Naomi Approved", "Sunset Views"],
    description: "San Francisco's very own urban cable gondola! The glass-walled cabin glides from street level at Salesforce Plaza up to the rooftop transit center park, providing a mini aerial flight above the city pavement.",
    tips: "Operates daily (typically 8am-8pm). Completely free to ride and fully wheelchair / stroller accessible."
  },
  {
    id: "deyoung-treasures-pharaohs",
    title: "Treasures of the Pharaohs at the De Young Museum",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: true,
    neighborhood: "Golden Gate Park, SF",
    address: "50 Hagiwara Tea Garden Dr, San Francisco, CA 94118",
    lat: 37.7715,
    lng: -122.4687,
    driveTime: "Local SF",
    duration: "2 - 3 hours",
    bestTime: "Early afternoon, followed by golden hour at the Hamon Observation Tower",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi can decode ancient hieroglyphic stamps, explore golden animal amulets (cats, falcons, scarabs), and pick up hands-on Egyptian craft kits in the museum store!",
    arseniyHighlights: "Take the glass elevator up to the 9th floor Hamon Observation Tower for free 360-degree sunset views of the Golden Gate Park canopy, Marin Headlands, and downtown SF.",
    arseniyFoodPick: "Head into Inner Sunset for a rich, velvety cappuccino at Andytown, or sip a West Coast Double IPA and juicy lamb burger at Sunset Reservoir Brewing Co.",
    joannaVeggiePick: "The De Young Cafe features a gorgeous outdoor courtyard serving roasted seasonal squash salads, wild mushroom flatbreads, and vegan grain bowls.",
    instagramHandle: "@bayareawilson",
    instagramUrl: "https://www.instagram.com/bayareawilson/",
    tags: ["Museum & Art", "Naomi Approved", "Family Fun", "Sunset Tower"],
    description: "An awe-inspiring immersion into ancient Egypt right in Golden Gate Park. Marvel at gold jewelry, painted sarcophagi, monumental granite statues, and sacred hieroglyphic papyri spanning three millennia.",
    tips: "Don't miss the free Hamon Tower observation deck before leaving — it has one of the finest 360-degree sunset vistas in SF and doesn't require museum admission!"
  },
  {
    id: "russian-hill-macondray-lane",
    title: "Russian Hill Hidden Stairways & Romantic Macondray Lane",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: true,
    neighborhood: "Russian Hill, SF",
    address: "Macondray Ln & Jones St, San Francisco, CA 94109",
    lat: 37.7995,
    lng: -122.4168,
    driveTime: "Local SF",
    duration: "1 - 1.5 hours",
    bestTime: "Golden hour when the bay shines emerald and twilight lanterns turn on",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi will love hunting for the hidden stone frog fountain, miniature fairy gardens, and secret wooden pedestrian bridges tucked between gingerbread cottages.",
    arseniyHighlights: "Steep cobblestone steps and secret terraces; romantic setting that served as Armistead Maupin's 'Barbary Lane' in Tales of the City.",
    arseniyFoodPick: "Walk down to Seven Hills for house-made pappardelle with slow-braised lamb ragu and a ribeye steak, or sip smoky artisanal mezcalitas at Mezcalito on Polk St.",
    joannaVeggiePick: "After the walk, stroll down to Fillmore or Polk for homemade vegetarian pasta at The Italian Homemade Company or matcha soft serve.",
    instagramHandle: "@humminglion",
    instagramUrl: "https://www.instagram.com/humminglion/",
    tags: ["Hidden Stairs", "Sunset Views", "Romantic Walk", "Naomi Approved"],
    description: "A magical pedestrian-only sanctuary tucked along the steep slope of Russian Hill. Wooden cobblestones, wisteria vines, historic gas lamps, and peek-a-boo vistas of Alcatraz and the sparkling bay make this one of SF's best-kept romantic secrets.",
    tips: "Combine with the Taylor Street steps and Vallejo Street summit for steep cardio and incredible skyline sunset panoramas."
  },
  {
    id: "golden-gate-bridge-walk",
    title: "Golden Gate Bridge Pedestrian Span & Vista Point",
    image: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: true,
    neighborhood: "Presidio / Marin Headlands",
    address: "Golden Gate Bridge Welcome Center, San Francisco, CA 94129",
    lat: 37.8199,
    lng: -122.4783,
    driveTime: "Local SF",
    duration: "1.5 - 2 hours",
    bestTime: "Golden hour (1 hour before sunset) as the towers glow blazing vermilion against the fog",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi can spot container ships passing 220 feet directly beneath her feet, listen to the booming fog horns, and touch the giant cross-section of the 36-inch suspension cables!",
    arseniyHighlights: "Walking across the international icon of the Bay; feel the sway of the bridge and take breathtaking photos looking back at the SF skyline.",
    arseniyFoodPick: "Feast at Dalida in the Presidio with wood-fired lamb shoulder and prime steaks, or cross into Sausalito for a barrel-aged sour beer at Barrel House Tavern.",
    joannaVeggiePick: "Warm up with hot apple cider and vegetarian cinnamon sugar churros or spiced oat lattes at the Round House Cafe at the bridge plaza.",
    instagramHandle: "@urbanhikersf",
    instagramUrl: "https://www.instagram.com/urbanhikersf/",
    tags: ["Iconic SF", "Sunset Views", "Family Friendly", "Naomi Approved"],
    description: "Suspended 220 feet above the Pacific tides, walking the Golden Gate Bridge offers unmatched vistas of the bay, Alcatraz, and the rolling Marin ridges. On clear or foggy evenings alike, the sunset light through the orange towers is pure cinema.",
    tips: "Bring windbreakers or warm layers — bridge winds can be brisk even on sunny afternoons. Pedestrian walkway is on the East side facing the bay."
  },
  {
    id: "skyline-watershed-ridge",
    title: "Skyline Watershed Ridge Trail (Fifield-Cahill Ridge)",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: true,
    neighborhood: "San Mateo Peninsula",
    address: "Skyline Blvd & Highway 92, San Mateo, CA 94402",
    lat: 37.5186,
    lng: -122.3785,
    driveTime: "30 - 35 min drive",
    duration: "2 - 3 hours",
    bestTime: "Late morning or late afternoon for crisp ridge visibility",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: false,
    naomiNote: "Naomi can bring binoculars to spot wild deer, red-tailed hawks, and banana slugs along the pristine forested path!",
    arseniyHighlights: "Peaceful, uncrowded ridge trail through protected old-growth Douglas firs, coastal scrub, and breathtaking panoramic views of Crystal Springs Reservoir and the Pacific.",
    arseniyFoodPick: "Stop in San Mateo at Wursthall for a thick grilled wagyu smash burger, bratwurst, and a rotating draft of Belgian sour ales and dank double IPAs.",
    joannaVeggiePick: "Pack a picnic with crusty sourdough, local cheeses, heirloom tomatoes, and dark chocolate to enjoy at the panoramic ridge overlook.",
    instagramHandle: "@bay_explorer",
    instagramUrl: "https://www.instagram.com/bay_explorer/",
    tags: ["Peninsula", "Nature Hike", "Scenic Ridge", "Naomi Approved"],
    description: "An untouched scenic ridge through the protected SFPUC peninsula watershed. This tranquil trail winds along the coastal spine between the Pacific Ocean and the sparkling Crystal Springs reservoirs.",
    tips: "Access is managed by the SFPUC — check open trailhead days or register for docent walks. Bring plenty of water and sun hats."
  },
  {
    id: "philmore-creamery",
    title: "Philmore Creamery Handcrafted Italian Gelato",
    image: "https://images.unsplash.com/photo-1560008511-11c63416e52d?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: true,
    neighborhood: "Pacific Heights / Fillmore, SF",
    address: "1840 Fillmore St, San Francisco, CA 94115",
    lat: 37.7885,
    lng: -122.4338,
    driveTime: "Local SF",
    duration: "30 - 45 minutes",
    bestTime: "Afternoon treat or post-dinner sweet stroll down Fillmore",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi will swoon over the Stracciatella, fresh Strawberry sorbetto, and Italian hazelnut waffle cones!",
    arseniyHighlights: "Silky, dense traditional Italian gelato churned in small batches with ultra-pure ingredients — try the Sicilian Bronte Pistachio and Dark Gianduja Chocolate.",
    arseniyFoodPick: "Arseniy double-espresso affogato poured over dark chocolate gianduja gelato, followed by a double West Coast IPA or smoky mezcal at The Snug down Fillmore.",
    joannaVeggiePick: "100% vegetarian friendly with an array of dairy-free fruit sorbettos (Passionfruit, Blood Orange, Raspberry) crafted with real fresh fruit.",
    instagramHandle: "@theres_a_food_for_that",
    instagramUrl: "https://www.instagram.com/theres_a_food_for_that/",
    tags: ["Artisanal Gelato", "Vegetarian Friendly", "Sweet Treats", "Naomi Approved"],
    description: "A beloved Fillmore destination specializing in authentic Italian gelato prepared according to Old World traditions. Known for its impossibly rich texture and intensely pure flavor profiles that transport you straight to Florence.",
    tips: "They happily offer samples so you can mix and match two or three flavors in one cup. Perfect stop after visiting Russian Hill or the Presidio."
  },

  // --- CONFIGURATION 1: URBAN HIKES, STAIRS & SUNSET VIEWS ---
  {
    id: "corona-heights-saturn-steps",
    title: "Vulcan & Saturn Street Secret Stairs to Corona Heights Summit",
    image: "https://images.unsplash.com/photo-1521464302861-ce943917d1c3?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Corona Heights / Castro, SF",
    address: "Vulcan Stairway & Ord St, San Francisco, CA 94114",
    lat: 37.7645,
    lng: -122.4412,
    driveTime: "Local SF",
    duration: "1.5 - 2 hours",
    bestTime: "Sunset golden hour (6:00 - 7:15 PM)",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Secret garden pathways lined with cottage birdhouses, winding stone steps, and friendly neighborhood cats who say hello.",
    arseniyHighlights: "High-cardio stair climb through lush redwood terraces opening suddenly to a rugged, Martian red-rock peak with dramatic 360° unobstructed SF panoramas.",
    arseniyFoodPick: "Descend into the Castro for a bone-in ribeye or grilled lamb skewers at Starbelly, paired with a Russian River Blind Pig IPA or barrel-aged sour ale.",
    joannaVeggiePick: "After descending to the Castro, grab dinner at Cafe Flore or enjoy vegan tacos and elote at Gracias Madre nearby on Mission.",
    instagramHandle: "@humminglion",
    instagramUrl: "https://www.instagram.com/humminglion/",
    tags: ["Stairs & Cardio", "360 Views", "Sunset Peak", "Hidden Gardens", "Arseniy Favorite"],
    description: "One of San Francisco's most enchanting urban treks. Climb the historic wooden stairways of Vulcan and Saturn Streets through lush cottage gardens and blooming bougainvillea, culminating at the jagged red chert summit of Corona Heights for legendary sunset vistas.",
    tips: "Wear shoes with good grip for the rocky summit ridge. Bring a light jacket as winds pick up when the sun dips behind Twin Peaks."
  },
  {
    id: "grand-view-park-tiled-steps",
    title: "Grand View Park (Turtle Hill) via 16th Ave & Hidden Garden Tiled Steps",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Golden Gate Heights / Sunset, SF",
    address: "Moraga St & 16th Ave, San Francisco, CA 94122",
    lat: 37.7562,
    lng: -122.4719,
    driveTime: "Local SF",
    duration: "1.5 hours",
    bestTime: "Sunset (arrive 45 mins before dusk to climb both mosaic staircases)",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi will be captivated counting the sea creatures, butterflies, hummingbirds, and sun stars hand-crafted into the colorful mosaic ceramic tiles!",
    arseniyHighlights: "Double staircase climb (163 mosaic steps at 16th Ave + 148 steps at Hidden Garden) ascending to a sandy hilltop ridge with infinite views from Golden Gate Bridge to the Pacific Ocean.",
    arseniyFoodPick: "Inner Sunset feast: grab an afternoon cortado at Snowbird Coffee, followed by dry-fried pork ribs and a cold DIPA at San Tung, or lamb burgers at Sunset Reservoir Brewing.",
    joannaVeggiePick: "Head down 9th Ave into Inner Sunset for San Tung's famous dry fried green beans or grab house-made vegetarian udon at Mugizo.",
    instagramHandle: "@urbanhikersf",
    instagramUrl: "https://www.instagram.com/urbanhikersf/",
    tags: ["Tiled Steps", "Sunset Views", "Arts & Mosaics", "Naomi Approved", "Epic Vista"],
    description: "Ascend 300+ dazzling handmade mosaic steps through neighborhood succulent gardens onto an ancient sand dune peak. At the summit bench, you have a majestic view over the entire Sunset district grid, Golden Gate Park, and the vast Pacific ocean at twilight.",
    tips: "Park near 16th & Moraga, climb the 16th Ave steps, explore the peak, and descend via the adjacent Hidden Garden steps on 15th Ave for the full loop."
  },
  {
    id: "bernal-heights-sunset-summit",
    title: "Bernal Heights Sunset Summit & Secret Rock Labyrinth",
    image: "https://images.unsplash.com/photo-1506146332389-18140dc7b2fb?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Bernal Heights, SF",
    address: "Bernal Heights Blvd, San Francisco, CA 94110",
    lat: 37.7431,
    lng: -122.4148,
    driveTime: "Local SF",
    duration: "1 - 1.5 hours",
    bestTime: "Golden hour into dusk when the city lights turn on",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: false,
    naomiNote: "Naomi can search for the secret stone rock labyrinth on the southern shoulder and watch dozens of friendly dogs playing on the grassy hill!",
    arseniyHighlights: "Find the famous lone eucalyptus tree with the rope swing overlooking the glittering downtown skyline and Salesforce Tower.",
    arseniyFoodPick: "Stroll Cortland Ave to Holy Water for artisanal mezcal & tequila cocktails, or grab a juicy double smash burger and hazy double IPA at Barebottle Brewing.",
    joannaVeggiePick: "Stroll down Cortland Ave to Pinhole Coffee for oat horchata or grab vegetarian wood-fired pizza at Vega.",
    instagramHandle: "@humminglion",
    instagramUrl: "https://www.instagram.com/humminglion/",
    tags: ["Sunset Views", "Skyline Views", "Dog Paradise", "Rope Swing", "Local Gem"],
    description: "A wild, windswept 360-degree hill rising above the Mission and Bernal neighborhoods. On clear golden evenings, the city skyline blazes amber while the Golden Gate Bridge and Bay Bridge flank either side.",
    tips: "Park along Bernal Heights Blvd and take the upper dirt path. Bring a cozy blanket to sit and watch the city transition from dusk to twilight."
  },
  {
    id: "presidio-batteries-to-bluffs",
    title: "Presidio Batteries to Bluffs Trail & Marshall's Beach",
    image: "https://images.unsplash.com/photo-1422493757035-1e5e03968f95?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Presidio, SF",
    address: "Lincoln Blvd & Langdon Ct, San Francisco, CA 94129",
    lat: 37.8016,
    lng: -122.4795,
    driveTime: "Local SF",
    duration: "2 hours",
    bestTime: "Sunset (1 hour before sunset to catch the golden light on the bluffs)",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi can explore historic military artillery batteries with hidden lookout bunkers and search for smooth beach sea glass.",
    arseniyHighlights: "The single best photography angle of the Golden Gate Bridge in SF: dramatic wooden stairs hugging steep coastal bluffs plunging down to Marshall's Beach.",
    arseniyFoodPick: "Post-hike feast at Dalida in the Presidio Main Post: wood-fired lamb shawarma flatbreads, charred steaks, and craft cocktails with single-estate mezcal.",
    joannaVeggiePick: "Head to Presidio Social Club or Dalida in the Main Post for Mediterranean roasted cauliflower, whipped feta, and house flatbreads.",
    instagramHandle: "@bayareawilson",
    instagramUrl: "https://www.instagram.com/bayareawilson/",
    tags: ["Coastal Stairs", "Golden Gate Views", "Sunset Beach", "Dramatic Cliffs", "Photography Hit"],
    description: "A breathtaking cliffside trail descending steep wooden stairways and coastal scrub directly toward the ocean. The secluded cove of Marshall's Beach offers intimate views of the Golden Gate Bridge glowing crimson against crashing Pacific waves.",
    tips: "Check tide charts — low tide is best for walking on the sand. The stairs back up provide a fantastic leg workout."
  },
  {
    id: "mount-davidson-cloud-forest",
    title: "Mount Davidson Cloud Forest & Cross Trail",
    image: "https://images.unsplash.com/photo-1511497584788-87676104235f?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Miraloma Park / Mt Davidson, SF",
    address: "Myra Way & Dalewood Way, San Francisco, CA 94127",
    lat: 37.7382,
    lng: -122.4542,
    driveTime: "Local SF",
    duration: "1.5 hours",
    bestTime: "Late afternoon as coastal fog whispers through eucalyptus treetops",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Feels like exploring an enchanted fairytale misty forest with winding trails, hollowed trees, and chirping songbirds.",
    arseniyHighlights: "Standing at the highest natural geographic point in San Francisco (928 ft) next to the towering 103-foot historic concrete monument with panoramic views toward Sutro Tower and downtown.",
    arseniyFoodPick: "West Portal stop: order a velvety cortado at Subconscious Coffee, followed by prime wood-grilled steaks and a heavy West Coast IPA at Elena or Trattoria da Vittorio.",
    joannaVeggiePick: "Visit nearby West Portal for toasted sesame vegetarian bagels or wood-fired pizzas with truffled mushrooms at Trattoria da Vittorio.",
    instagramHandle: "@urbanhikersf",
    instagramUrl: "https://www.instagram.com/urbanhikersf/",
    tags: ["Cloud Forest", "Highest SF Peak", "Misty Trails", "Hidden Gem", "Sunset Views"],
    description: "San Francisco's highest peak is crowned by a dense, tranquil forest of century-old Tasmanian blue gum eucalyptus trees. Sunlight filters through foggy canopy leaves onto rocky ridges with sweeping vistas of the southern hills and bay.",
    tips: "Access the trail from the Dalewood Way entrance. Forest trails can be damp and cool, so dress in layers."
  },
  {
    id: "tank-hill-kite-hill",
    title: "Tank Hill & Kite Hill Secret Twin Ridges",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Cole Valley / Castro, SF",
    address: "Twin Peaks Blvd & Crown Ter, San Francisco, CA 94114",
    lat: 37.7595,
    lng: -122.4468,
    driveTime: "Local SF",
    duration: "1 hour",
    bestTime: "Sunset into dusk",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Hunting for native wildflowers (purple lupines and California poppies) and climbing the gentle rocky outcrop.",
    arseniyHighlights: "The local insider alternative to tourist-heavy Twin Peaks — unobstructed cinematic view looking down Cole Valley straight out to the Golden Gate Bridge.",
    arseniyFoodPick: "Walk into Cole Valley for dry-aged bavette steak frites at Zazie, followed by a glass of rare Belgian lambic sour beer or strong IPA at Finnegans Wake.",
    joannaVeggiePick: "Walk down into Cole Valley for Zazie's famous vegetarian wild mushroom polenta or roasted butternut squash tart.",
    instagramHandle: "@humminglion",
    instagramUrl: "https://www.instagram.com/humminglion/",
    tags: ["Secret Overlook", "Sunset Spot", "Cole Valley", "Skyline Panorama", "Intimate View"],
    description: "Perched high above Cole Valley, Tank Hill is named for the historic water storage tank that once sat here. Today, its eucalyptus bench and rocky outcropping provide one of the city's most peaceful and romantic perches for twilight city watching.",
    tips: "Follow the hidden wooden stairs off Twin Peaks Blvd. A fantastic spot for bringing a thermos of tea or wine for sunset."
  },
  {
    id: "hawk-hill-battery-spencer",
    title: "Hawk Hill & Battery Spencer Sunset Ridge",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Marin Headlands",
    address: "Conzelman Rd, Sausalito, CA 94965",
    lat: 37.8279,
    lng: -122.4994,
    driveTime: "25 min drive across Golden Gate Bridge",
    duration: "1.5 - 2 hours",
    bestTime: "Sunset golden hour (arrive 1 hour before sunset for parking)",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: false,
    naomiNote: "Naomi can spot migrating raptors (red-tailed hawks, peregrine falcons, and golden eagles) riding wind thermals right over the ridge at Hawk Watch!",
    arseniyHighlights: "Dramatic cliffside road with jaw-dropping views looking directly down onto the Golden Gate Bridge cables with the entire SF skyline floating behind it in golden fog.",
    arseniyFoodPick: "Drive down into Sausalito for Copita Tequileria y Comida: artisanal smoky mezcal flights, grilled steak tacos, and fresh morning cortados.",
    joannaVeggiePick: "Drive 10 minutes down into charming Sausalito for waterfront vegetarian mezze platters, hummus, and falafel at Falafel Hut or Copita Tequileria.",
    instagramHandle: "@bay_explorer",
    instagramUrl: "https://www.instagram.com/bay_explorer/",
    tags: ["Marin Headlands", "World Class Sunset", "Raptor Watching", "Golden Gate Icon", "Day Trip"],
    description: "Arguably the most cinematic viewpoint on the West Coast. Standing atop the Marin Headlands bluffs, watch the pacific fog roll through the Golden Gate straits while the setting sun bathes the bridge towers and city towers in pink and orange neon.",
    tips: "Dress warmly — high bluff winds are frequent. Bring a camera with zoom capabilities for iconic photos."
  },
  {
    id: "mount-tam-east-peak",
    title: "Mount Tamalpais East Peak & Rock Spring Sunset Trail",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Marin County / Mill Valley",
    address: "East Peak Parking, Mt Tamalpais State Park, Mill Valley, CA 94941",
    lat: 37.9235,
    lng: -122.5779,
    driveTime: "50 min drive",
    duration: "2 - 3 hours",
    bestTime: "Sunset — watching the sunset ABOVE the cloud layer",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi will be thrilled by the historic mountain fire lookout tower perched on the highest rock crag and the 1890s gravity railroad museum at the depot!",
    arseniyHighlights: "Standing 2,571 feet above sea level with a view of the sunset sinking into a literal ocean of white marine fog beneath you, with Farallon Islands in the distance.",
    arseniyFoodPick: "Mill Valley pit stop: Tam Commons taproom for rotating barrel-aged wild sours, Pliny the Elder DIPA, and prime steak burgers or slow-roasted lamb.",
    joannaVeggiePick: "Stop in Mill Valley on the way down for dinner at Prabh Indian Kitchen or vegetable enchiladas at Joe's Taco Lounge.",
    instagramHandle: "@bay_explorer",
    instagramUrl: "https://www.instagram.com/bay_explorer/",
    tags: ["Above the Clouds", "Highest Peak", "Epic Sunset", "Marin Day Trip", "Bucket List"],
    description: "A transcendent experience: when San Francisco is blanketed in low fog, Mount Tamalpais East Peak rises completely above the clouds into bright sunshine. The Verna Dunshee loop trail circles the summit crags with views stretching all the way to the Sierra Nevada on crystal clear days.",
    tips: "There is an \$8 park entrance fee for East Peak parking. Bring flashlights or headlamps for walking back to the car after sunset."
  },
  {
    id: "cataract-falls-alpine-lake",
    title: "Cataract Falls & Alpine Lake Mossy Redwood Trail",
    image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
    category: "hike",
    spreadsheetItem: false,
    neighborhood: "Mount Tamalpais Watershed / Bolinas",
    address: "Bolinas-Fairfax Rd, Stinson Beach, CA 94970",
    lat: 37.9348,
    lng: -122.6163,
    driveTime: "50 min drive",
    duration: "2.5 - 3 hours",
    bestTime: "Late morning to mid-afternoon for dappled sunbeams through redwoods",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: false,
    naomiNote: "Naomi can search for bright yellow banana slugs, newts swimming in creek pools, and climb rustic wooden footbridges over bubbling waterfalls!",
    arseniyHighlights: "Stunning series of rushing waterfalls cascading down a moss-draped redwood ravine with stone staircases built into the forest floor.",
    arseniyFoodPick: "Stop at Gestalt Haus in Fairfax for smoked brats, artisanal sour beers on tap, and strong double IPAs on the sunny outdoor deck.",
    joannaVeggiePick: "Head to the charming town of Fairfax for delicious organic vegetarian fare at The Good Earth Natural Foods or vegetarian sourdough pizza at Gestalt Haus.",
    instagramHandle: "@bay_explorer",
    instagramUrl: "https://www.instagram.com/bay_explorer/",
    tags: ["Waterfalls", "Redwood Forest", "Marin Watershed", "Banana Slugs", "Naomi Approved"],
    description: "One of the most lush, fairytale-like waterfall hikes in Northern California. Cataract Creek cascades down the northwest flank of Mount Tamalpais toward Alpine Lake through an emerald canyon of ferns, mossy boulders, and towering coastal redwoods.",
    tips: "Parking along Bolinas-Fairfax Road is limited; arrive before 10 AM on weekends or enjoy a peaceful weekday hike."
  },

  // --- CONFIGURATION 2: SMASH BURGERS, ARTISANAL TREATS & HIDDEN GEM CAFES ---
  {
    id: "beeps-burgers",
    title: "Beep's Burgers 1962 Vintage Drive-In",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Ingleside / Ocean Ave, SF",
    address: "1051 Ocean Ave, San Francisco, CA 94112",
    lat: 37.7236,
    lng: -122.4548,
    driveTime: "Local SF",
    duration: "45 minutes",
    bestTime: "Lunch or late-night craving under the glowing neon sign",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi can get chocolate malt milkshakes topped with whipped cream, golden crinkle-cut fries, and crispy onion rings.",
    arseniyHighlights: "Arseniy's Smash Burger Hit: The Beep's 1/4 lb Double Cheeseburger with razor-thin crispy smashed edges, gooey American cheese, grilled onions, pickles, and Beep's secret sauce on toasted brioche.",
    arseniyFoodPick: "Arseniy Smash Burger Hit: The Beeps 1/4 lb Double Cheeseburger with razor-thin crispy smashed edges, gooey American cheese, grilled onions, and secret sauce on toasted brioche.",
    joannaVeggiePick: "Joanna's Veggie Pick: Beep's Dedicated Impossible Cheeseburger — griddled to perfection with melting cheese, grilled caramelized onions, house special sauce, and crisp lettuce!",
    instagramHandle: "@bayarea.foodies",
    instagramUrl: "https://www.instagram.com/bayarea.foodies/",
    tags: ["Smash Burger Hit", "Vegetarian Pick", "Vintage Drive-In", "Arseniy Favorite", "Iconic SF"],
    description: "An SF institution since 1962, Beep's serves legendary old-school smash burgers beneath a retro space-age neon beacon on Ocean Avenue. Consistently ranked by food critics as one of the very best burgers in Northern California.",
    tips: "Order at the walk-up window and enjoy your burger hot in the car or at the sidewalk seating."
  },
  {
    id: "causwells-americana",
    title: "Causwells & The Legendary Americana Smash Burger",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Marina District / Chestnut St, SF",
    address: "2346 Chestnut St, San Francisco, CA 94123",
    lat: 37.8005,
    lng: -122.4414,
    driveTime: "Local SF",
    duration: "1.5 hours",
    bestTime: "Dinner / Evening date night followed by a walk along the Marina Green",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi will love the crispy house fries with garlic dipping sauce and warm chocolate chip skillet cookie with vanilla bean ice cream!",
    arseniyHighlights: "Arseniy's Smash Burger Hit: The 'Americana Burger' — two seasoned smash patties, American cheese, Causwells secret sauce, lacto-fermented dill pickles, and crispy smashed onion strings on a pillowy bun. Regarded as the undisputed gold standard in SF.",
    arseniyFoodPick: "Arseniy Smash Burger Hit: The legendary Americana Burger with crispy onions and house sauce, washed down with a cold draft West Coast Double IPA or smoky mezcalita.",
    joannaVeggiePick: "Joanna's Veggie Pick: Causwells House Veggie Burger — crafted from roasted black beans, grains, and mushrooms, topped with aged cheddar, pickled red onions, and herb aioli; plus charred lemon broccolini and rosemary truffle fries!",
    instagramHandle: "@andreweatsinsf",
    instagramUrl: "https://www.instagram.com/andreweatsinsf/",
    tags: ["Gold Standard Burger", "Vegetarian Pick", "Marina Date Night", "Chestnut St", "Arseniy Favorite"],
    description: "Chef Adam Rosenblum's cozy Northern California bistro has achieved legendary status among burger aficionados for the Americana Burger. With a lively neighborhood patio on vibrant Chestnut Street, it's the ultimate date spot.",
    tips: "Reserve an outdoor patio table on Resy or grab walk-in bar seats. Pair with their craft local beer or seasonal cocktails."
  },
  {
    id: "bandit-dogpatch",
    title: "Bandit & The Forager Brioche Brunch",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Dogpatch / Lower Nob Hill, SF",
    address: "908 Geary St, San Francisco, CA 94109",
    lat: 37.7862,
    lng: -122.4184,
    driveTime: "Local SF",
    duration: "1 hour",
    bestTime: "Weekend morning or casual Friday lunch",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi will love the Tater Tots loaded with melted cheese and fresh strawberry lemonade.",
    arseniyHighlights: "Arseniy's Smash Burger Hit: 'The Bandit' — smashed wagyu beef blend, caramelized onions, bacon jam, cheddar, and house garlic aioli on a toasted brioche bun.",
    arseniyFoodPick: "Arseniy Smash Burger Hit: The Bandit with smashed wagyu, caramelized onions, bacon jam, and garlic aioli, paired with a rich double-shot cortado.",
    joannaVeggiePick: "Joanna's Veggie Pick: 'The Forager' — soft scrambled cage-free eggs, sautéed wild forest mushrooms, baby arugula, havarti cheese, and truffle aioli on toasted brioche; or their Impossible smash patty upgrade!",
    instagramHandle: "@andreweatsinsf",
    instagramUrl: "https://www.instagram.com/andreweatsinsf/",
    tags: ["Smash Burger Hit", "Vegetarian Pick", "Artisan Brioche", "Brunch Gem", "Dogpatch"],
    description: "Famous for hyper-satisfying smash burgers and elevated breakfast sandwiches served on golden toasted brioche. Bandit balances deeply savory burger craftsmanship with gourmet vegetarian creations.",
    tips: "Pair with an iced horchata latte or house-brewed ginger mint tea."
  },
  {
    id: "lovelys-emeryville",
    title: "Lovely's Oklahoma-Style Onion Smash Burgers",
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Emeryville / Oakland",
    address: "Inside Two Pitchers Brewing, 2344 Webster St, Oakland, CA 94612",
    lat: 37.8136,
    lng: -122.2642,
    driveTime: "25 min drive across Bay Bridge",
    duration: "1.5 hours",
    bestTime: "Sunny weekend afternoon in the spacious outdoor beer garden",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Spacious outdoor beer garden with lawn games, soft pretzels with cheddar cheese sauce, and non-alcoholic house root beer on tap!",
    arseniyHighlights: "Arseniy's Smash Burger Hit: The 'Drive-Thru Burger' — authentic Oklahoma-style paper-thin shaved onions pressed directly into the smash beef on the scorching flat top until caramelized and lacey-crisp, with double American cheese and yellow mustard.",
    arseniyFoodPick: "Arseniy Smash Burger Hit: Oklahoma-style onion smash burger on a potato bun, washed down with Two Pitchers tart sour beer or double IPA on tap.",
    joannaVeggiePick: "Joanna's Veggie Pick: The Crispy Fried Green Tomato Sandwich with pimento cheese and spicy remoulade, OR the House Veggie Smash with griddled onions and dill pickles + malt vinegar crinkle fries!",
    instagramHandle: "@bayarea.foodies",
    instagramUrl: "https://www.instagram.com/bayarea.foodies/",
    tags: ["Oklahoma Smash", "East Bay Day Trip", "Outdoor Garden", "Vegetarian Pick", "Arseniy Favorite"],
    description: "Tucked inside the lively Two Pitchers Brewing beer hall and outdoor courtyard, Lovely's serves some of the most celebrated retro flat-top smash burgers in the entire Bay Area, drawing passionate foodies from across Northern California.",
    tips: "Plenty of covered outdoor picnic tables with fire pits for chilly evenings. Very family-friendly."
  },
  {
    id: "smitten-ice-cream-hayes",
    title: "Smitten Ice Cream & Hayes Valley Square",
    image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Hayes Valley, SF",
    address: "432 Octavia St #1A, San Francisco, CA 94102",
    lat: 37.7766,
    lng: -122.4245,
    driveTime: "Local SF",
    duration: "45 minutes",
    bestTime: "Afternoon sun or post-dinner stroll under Hayes Valley fairy lights",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi can watch the magic cryogenic liquid-nitrogen churn churning liquid cream into fresh frozen ice cream in under 90 seconds with clouds of cool mist!",
    arseniyHighlights: "Freshly made-to-order ice cream churned at minus 321°F for microscopic ice crystals that create the smoothest texture imaginable — try the Cookie Dough with Pretzels and Brookies.",
    arseniyFoodPick: "Order a rich double-shot cappuccino at Blue Bottle or Ritual nearby, or hop over to Brass Tacks in Hayes Valley for an artisanal mezcal and tequila flight.",
    joannaVeggiePick: "100% vegetarian friendly with seasonal vegan coconut-based creations (Fresh Strawberry White Balsamic and Earl Grey with dark chocolate flakes).",
    instagramHandle: "@theres_a_food_for_that",
    instagramUrl: "https://www.instagram.com/theres_a_food_for_that/",
    tags: ["Liquid Nitrogen", "Artisanal Ice Cream", "Hayes Valley", "Naomi Approved", "Vegetarian Friendly"],
    description: "Born in San Francisco, Smitten reimagined ice cream making with patented liquid-nitrogen churning technology. Flavors are spun fresh right in front of your eyes from pure, organic California dairy and seasonal farm ingredients.",
    tips: "Eat your cone on the Patricia's Green lawn in Hayes Valley while looking at the rotating community art installations."
  },
  {
    id: "home-cafe-birthday-latte",
    title: "Home Cafe & Arseniy's 32nd Birthday Cake Latte",
    image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Outer Sunset / Noriega, SF",
    address: "1222 Noriega St, San Francisco, CA 94122",
    lat: 37.7541,
    lng: -122.4764,
    driveTime: "Local SF",
    duration: "1 hour",
    bestTime: "Morning coffee date or mid-day sweet boost",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi can get the warm Cookie Monster hot chocolate or Red Velvet latte topped with handmade rainbow foam art and sprinkles!",
    arseniyHighlights: "Arseniy's 32nd Birthday Special: Order the famous 'Birthday Cake Latte' served with rainbow sprinkles and vanilla cake batter sweetness, or the Sea Salt Caramel Lavender Latte.",
    arseniyFoodPick: "Arseniy 32nd Birthday Special: Birthday Cake Latte or velvety cortado, followed by a visit to Woods Outbound on Judah for house-brewed sour beers and strong IPAs.",
    joannaVeggiePick: "Joanna's Veggie Pick: Gourmet artisanal toast flights — Creamy Avocado Toast with poached egg & microgreens, and Sweet Ricotta Toast with local honey and sliced strawberries on fresh levain bread.",
    instagramHandle: "@theres_a_food_for_that",
    instagramUrl: "https://www.instagram.com/theres_a_food_for_that/",
    tags: ["Birthday Special", "Artisan Coffee", "Toast Flights", "Outer Sunset", "Aesthetic Cafe"],
    description: "A whimsical, ultra-creative cafe famous for edible art. Their baristas craft intricate latte foam designs and unexpected flavor combinations alongside hearty, photogenic sourdough toast flights.",
    tips: "Only a few blocks from Ocean Beach — grab your festive drinks to go and take a walk on the sand dunes."
  },
  {
    id: "outerlands-ocean-beach",
    title: "Outerlands Driftwood Haven & Ocean Beach Dunes",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Outer Sunset / Ocean Beach, SF",
    address: "4001 Judah St, San Francisco, CA 94122",
    lat: 37.7602,
    lng: -122.5052,
    driveTime: "Local SF",
    duration: "1.5 - 2 hours",
    bestTime: "Cozy dinner as coastal fog rolls in, followed by sunset beach walk",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Warm driftwood interior feels like being inside a whimsical cedar ship; enjoy hot apple cider and chocolate chip sea-salt cookies.",
    arseniyHighlights: "Intimate rustic design with cedar driftwood reclaimed from Northern California beaches, serving local craft beer, cider, and hearty organic dishes.",
    arseniyFoodPick: "Slow-braised lamb belly or wood-roasted steak with seasonal jus, accompanied by rustic sourdough, a natural sour ale, or a velvety double cappuccino.",
    joannaVeggiePick: "Joanna's Veggie Pick: Outerlands' legendary house-baked levain Grilled Cheese on thick sourdough with organic heirloom tomato soup, seasonal roasted Romanesco with chimichurri, and ricotta gnudi!",
    instagramHandle: "@andreweatsinsf",
    instagramUrl: "https://www.instagram.com/andreweatsinsf/",
    tags: ["Hidden Gem Cafe", "Ocean Beach", "Vegetarian Feast", "Cozy Date Night", "Sunset Vibe"],
    description: "Perched just two blocks from the roaring Pacific Ocean at the end of the N-Judah line, Outerlands is one of SF's most beloved sanctuaries. Built entirely with reclaimed weathered wood, it radiates warmth, comfort, and farm-to-table culinary brilliance.",
    tips: "Put your name on the list and take a sunset stroll along Ocean Beach dunes while waiting for your table."
  },
  {
    id: "tartine-manufactory-mission",
    title: "Tartine Manufactory & Wood-Fired Evening",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Mission District, SF",
    address: "591 Alabama St, San Francisco, CA 94110",
    lat: 37.7618,
    lng: -122.4124,
    driveTime: "Local SF",
    duration: "1.5 hours",
    bestTime: "Brunch or early dinner when bakery ovens glow with fresh loaves",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi can watch the bakers knead dough and shape pastries through the glass kitchen, plus enjoy hot cocoa and chocolate hazelnut brioche.",
    arseniyHighlights: "The Mecca of sourdough bread: towering light-filled industrial cathedral with rotating local beers, house-cured meats, and warm country loaves with cultured butter.",
    arseniyFoodPick: "Prime flat iron steak with salsa verde, wood-fired lamb flatbread, and a rich double espresso cortado from their Coffee Manufactory roastery.",
    joannaVeggiePick: "Joanna's Veggie Pick: Wood-fired seasonal mushroom and fontina flatbread, burrata with persimmon and pistachios, roasted cauliflower with Meyer lemon, and fresh morning buns!",
    instagramHandle: "@valenciacorridorsf",
    instagramUrl: "https://www.instagram.com/valenciacorridorsf/",
    tags: ["World Class Bakery", "Mission District", "Vegetarian Feast", "Date Night", "Wood Fired"],
    description: "Tartine's 5,000-square-foot flagship bakery, cafe, and restaurant in the Mission. Flooded with natural light through massive industrial windows, it showcases the pinnacle of California sourdough baking and vegetable-forward culinary craft.",
    tips: "Pick up a whole loaf of fresh country bread to take home. Walk around the corner to see the Mission murals on 18th St."
  },
  {
    id: "song-tea-ceramics",
    title: "Song Tea & Handmade Ceramic Tasting Flight",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Lower Pacific Heights, SF",
    address: "2120 Sutter St, San Francisco, CA 94115",
    lat: 37.7854,
    lng: -122.4347,
    driveTime: "Local SF",
    duration: "1 hour",
    bestTime: "Calm weekday afternoon or quiet Saturday morning",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi can examine the delicate handcrafted ceramic tea cups, tea pets (little clay animals), and watch leaves unfurl in glass beakers.",
    arseniyHighlights: "Rare, exquisite loose-leaf oolongs, aged pu-erhs, and roasted teas sourced directly from remote Taiwanese and Chinese mountain farms; prepared with reverent precision.",
    arseniyFoodPick: "Follow up tea tasting with a visit to The Snug on Fillmore for artisanal mezcal, aged tequila copitas, and dry-aged wagyu smash burgers.",
    joannaVeggiePick: "100% pure plant-based botanical teas — try the Gold Dragon Oolong and fragrant wild garden herbal infusions.",
    instagramHandle: "@theres_a_food_for_that",
    instagramUrl: "https://www.instagram.com/theres_a_food_for_that/",
    tags: ["Tea Tasting", "Artisan Ceramics", "Peaceful Sanctuary", "Hidden Gem", "Mindful Date"],
    description: "A serene, minimalist temple of tea culture founded by Peter Luong. Song Tea procures micro-lots of rare traditional and experimental teas, served in one-of-a-kind handmade ceramic gaiwans crafted by independent ceramicists.",
    tips: "Book a private tasting session in advance for an unforgettable guided multi-steep flight."
  },
  {
    id: "dandelion-chocolate-valencia",
    title: "Dandelion Chocolate Factory & Valencia Stroll",
    image: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&auto=format&fit=crop&q=80",
    category: "food",
    spreadsheetItem: false,
    neighborhood: "Mission District / Valencia Corridor, SF",
    address: "2600 16th St, San Francisco, CA 94103",
    lat: 37.7656,
    lng: -122.4158,
    driveTime: "Local SF",
    duration: "1 - 1.5 hours",
    bestTime: "Afternoon sweet exploration before exploring Valencia Street shops",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi can taste bean-to-bar chocolate samples from Madagascar and Ecuador and enjoy European-style hot chocolate with house-torched marshmallows!",
    arseniyHighlights: "Single-origin chocolate tasting salon where you can see the roaring roaster, winnower, and melangers grinding cocoa beans behind brass railings.",
    arseniyFoodPick: "Valencia Corridor crawl: smoky Oaxacan mezcal tasting at Laszlo or ABV, paired with grilled lamb tacos or a thick wood-grilled ribeye at Loló.",
    joannaVeggiePick: "Joanna's Veggie Pick: 100% vegetarian artisan confections with dairy-free dark chocolate bars, vegan molten chocolate cookies, and oat milk hot chocolate flights.",
    instagramHandle: "@valenciacorridorsf",
    instagramUrl: "https://www.instagram.com/valenciacorridorsf/",
    tags: ["Bean to Bar", "Valencia Corridor", "Hot Chocolate Flight", "Naomi Approved", "Date Walk"],
    description: "A bean-to-bar craft chocolate maker that produces single-origin chocolate bars using only two ingredients: cocoa beans and organic sugar. Sip on their signature hot chocolate flights in the Bloom Salon before exploring the quirky boutiques of Valencia.",
    tips: "Walk down Valencia St afterward to visit Paxton Gate oddities shop and Clarion Alley street art murals."
  },

  // --- CONFIGURATION 3: FAMILY-FRIENDLY ADVENTURES WITH NAOMI (ANIMALS & CRAFTS) ---
  {
    id: "harley-farms-goat-dairy",
    title: "Harley Farms Goat Dairy & Pasture Tour",
    image: "https://images.unsplash.com/photo-1524024973431-2ad916746881?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Pescadero Coast",
    address: "205 North St, Pescadero, CA 94060",
    lat: 37.2543,
    lng: -122.3831,
    driveTime: "55 min drive south along Highway 1",
    duration: "2 - 3 hours",
    bestTime: "Saturday or Sunday mid-morning when baby goats are most playful",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: false,
    naomiNote: "Naomi's Animal Dream: Hands-on petting and cuddling with friendly baby dairy goats, visiting the llama guardians, and watching the goats romp through the green coastal pasture!",
    arseniyHighlights: "Tour the historic 1910 Victorian dairy barn, see the copper cheese vats, and sample award-winning fresh chevre adorned with edible wildflower petals.",
    arseniyFoodPick: "Head into Pescaderos historic Duartes Tavern for grilled lamb chops, warm olallieberry pie, and a cold coastal IPA on tap.",
    joannaVeggiePick: "Joanna's Veggie Pick: Fresh garden herb and lavender honey chevre cheese picnic with crusty local sourdough from Arcangeli Grocery down the street in Pescadero.",
    instagramHandle: "@bayareawilson",
    instagramUrl: "https://www.instagram.com/bayareawilson/",
    tags: ["Feed & Pet Goats", "Pescadero Coast", "Scenic Drive", "Naomi's Animal Hit", "Cheese Picnic"],
    description: "A working goat dairy farm set in the bucolic coastal hamlet of Pescadero. Home to over 200 Alpine goats, a pair of watchful llamas, and barn owls. Visitors can stroll through historic pastures, pet friendly goats, and pick up fresh farmstead cheeses.",
    tips: "Combine with a scenic drive down Highway 1 through Half Moon Bay. Stop by Arcangeli Grocery in town for warm garlic herb artichoke bread."
  },
  {
    id: "slide-ranch-coastal-farm",
    title: "Slide Ranch & Coastal Farm Tidepool Adventure",
    image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Muir Beach / Marin Coast",
    address: "2025 Shoreline Hwy, Muir Beach, CA 94965",
    lat: 37.8631,
    lng: -122.5855,
    driveTime: "40 min drive through Marin Headlands",
    duration: "2.5 - 3 hours",
    bestTime: "Weekend morning / low tide for exploring ocean tidepools",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: true,
    naomiNote: "Naomi's Animal & Craft Hit: Hand-feed heritage chickens, collect fresh warm eggs, milk friendly dairy goats, and make organic wool felt crafts!",
    arseniyHighlights: "Hiking along jaw-dropping coastal cliffs overlooking the Pacific Ocean, exploring ocean caves, and watching sea birds soar over the surf.",
    arseniyFoodPick: "Stop by the Pelican Inn at Muir Beach for English draft ales, roast prime beef with Yorkshire pudding, or braised lamb shank in a 16th-century style tavern.",
    joannaVeggiePick: "Pack a vegetarian coastal picnic with farm-fresh fruit, cheeses, and crusty bread to enjoy on the ocean-view picnic tables.",
    instagramHandle: "@bay_explorer",
    instagramUrl: "https://www.instagram.com/bay_explorer/",
    tags: ["Feed Animals", "Coastal Farm", "Tidepools", "Wool Crafts", "Naomi's Animal Hit"],
    description: "An educational organic ranch perched on dramatic cliffs above the crashing Pacific near Muir Beach. Kids and families connect directly with agriculture, feeding farm animals, harvesting garden herbs, and exploring coastal tidepools below.",
    tips: "Check the Slide Ranch event calendar for family farm day workshops. Wear sturdy shoes for the dirt path down to the ocean."
  },
  {
    id: "deer-hollow-farm-rancho",
    title: "Deer Hollow Farm & Rancho San Antonio Trail",
    image: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Cupertino / Los Altos Hills",
    address: "22500 Cristo Rey Dr, Los Altos, CA 94024",
    lat: 37.3347,
    lng: -122.0863,
    driveTime: "45 min drive south down 280",
    duration: "2.5 hours",
    bestTime: "Morning (9:30 - 11:30 AM) when farm animals are out grazing in the corrals",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: false,
    naomiNote: "Naomi can meet and observe farm pigs, sheep, goats, chickens, ducks, and draft horses in a historic 160-year-old homestead setting!",
    arseniyHighlights: "Gentle, shady 1-mile flat walking trail through oak woodlands alongside wild deer and wild turkeys leading to the farm.",
    arseniyFoodPick: "Drive to Downtown Los Altos for State of Mind Public House: award-winning West Coast double IPAs, kettle sours, and prime smash burgers.",
    joannaVeggiePick: "Stop in nearby Mountain View on Castro Street for delicious South Indian vegetarian dosas and sambar at Madras Cafe.",
    instagramHandle: "@bayareawilson",
    instagramUrl: "https://www.instagram.com/bayareawilson/",
    tags: ["Historic Farm", "Friendly Farm Animals", "Shady Trail", "Wild Deer", "Naomi Approved"],
    description: "A 160-year-old historic working homestead nestled inside Rancho San Antonio Open Space Preserve. Reachable via a scenic family walking trail, the farm is home to sheep, pigs, goats, chickens, and organic community gardens.",
    tips: "No cars are allowed at the farm itself — park at the Rancho San Antonio main lot and take the easy 1-mile paved trail. Free admission."
  },
  {
    id: "aratas-pumpkin-farm-corral",
    title: "Arata's Animal Petting Corral & Minotaur's Labyrinth",
    image: "https://images.unsplash.com/photo-1508873696983-2df5703bc225?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Half Moon Bay",
    address: "185 Verde Rd, Half Moon Bay, CA 94019",
    lat: 37.4278,
    lng: -122.4285,
    driveTime: "40 min drive down the coast",
    duration: "2 - 3 hours",
    bestTime: "Sunny weekend morning or early afternoon",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: true,
    naomiNote: "Naomi's Animal Feeding Hit: Purchase feed cups to hand-feed friendly miniature goats, sheep, bunnies, and pony rides, plus navigate the giant 2-acre Minotaur hay maze!",
    arseniyHighlights: "Conquer the world-famous Minotaur's Labyrinth hay maze — a towering 6-foot tall puzzle with hidden corridors, wooden lookout bridges, and golden minotaur statutes.",
    arseniyFoodPick: "Stop by Hop Dogma Brewing in Half Moon Bay for world-class sour ales and murky double IPAs, paired with a prime grilled steak or burger.",
    joannaVeggiePick: "After the farm, drive 5 minutes into Half Moon Bay for fresh vegetarian fish-free tacos or hot clam-free chowder & sourdough at Sam's Chowder House patio.",
    instagramHandle: "@bayareawilson",
    instagramUrl: "https://www.instagram.com/bayareawilson/",
    tags: ["Feed Animals", "Hay Maze", "Petting Zoo", "Half Moon Bay", "Naomi's Animal Hit"],
    description: "The oldest working farm on the San Mateo County coast (established 1932). Features an interactive animal feeding corral, hay rides, train rides, and the legendary 2-acre Minotaur's Labyrinth hay maze built from thousands of bales of hay.",
    tips: "Bring cash or card for animal feed cups and maze tickets. Afterwards, catch the sunset at Half Moon Bay Coastal Trail."
  },
  {
    id: "randall-museum-corona",
    title: "Randall Museum & Live Rescued Animal Encounters",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Corona Heights, SF",
    address: "199 Museum Way, San Francisco, CA 94114",
    lat: 37.7648,
    lng: -122.4388,
    driveTime: "Local SF",
    duration: "1.5 - 2 hours",
    bestTime: "Saturday afternoon (free drop-in science and craft workshops)",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: true,
    naomiNote: "Naomi can meet live rescued California wildlife (barn owls, desert tortoises, snakes, gophers), watch animal feeding presentations, and join Saturday family craft classes in the art wing!",
    arseniyHighlights: "Interactive exhibits on SF geology and earthquakes, model train layouts, and panoramic outdoor terrace looking out over downtown SF.",
    arseniyFoodPick: "Walk down to Toronado in the Lower Haight: SFs legendary beer mecca with 40+ taps of world-famous sour beers (Russian River, Cantillon) and Blind Pig DIPA.",
    joannaVeggiePick: "Cafe R Café inside the museum serves delicious vegetarian paninis, avocado wraps, and fresh baked cookies.",
    instagramHandle: "@secret_sanfrancisco",
    instagramUrl: "https://www.instagram.com/secret_sanfrancisco/",
    tags: ["Rescued Animals", "Free Museum", "Hands-on Crafts", "Corona Heights", "Naomi Approved"],
    description: "A beloved SF community science, nature, and arts center perched directly beneath the rocky red cliffs of Corona Heights. Home to over 100 rescued native animals unable to survive in the wild, plus an operational woodworking shop and art studio.",
    tips: "Admission is 100% free! Pair directly with the short 10-minute walk up to Corona Heights summit for sunset."
  },
  {
    id: "sequoia-fabrica-craft-workshop",
    title: "Sequoia Fabrica Community Arts & Maker Workshop",
    image: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Potrero Hill / Mission, SF",
    address: "1736 18th St, San Francisco, CA 94107",
    lat: 37.7630,
    lng: -122.4005,
    driveTime: "Local SF",
    duration: "2 - 3 hours",
    bestTime: "Weekend community open craft days and hands-on workshops",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi's Arts & Crafts Dream: Hands-on screen printing on tote bags, making handmade journals and bookbinding, polymer clay sculpting, and block printing colorful patterns!",
    arseniyHighlights: "Inspiring community maker co-op filled with vintage printmaking presses, laser cutters, woodworking benches, and textile looms run by passionate local artisans.",
    arseniyFoodPick: "Walk into Potrero Hill to Foxsister or Chez Maman for grilled lamb chops, charred bavette steak, and an afternoon espresso cortado at Farleys.",
    joannaVeggiePick: "Walk over to Potrero Hill's 18th Street for Plow's seasonal vegetarian breakfast or delicious plant-based dishes at Chez Maman.",
    instagramHandle: "@sequoia.fabrica",
    instagramUrl: "https://www.instagram.com/sequoia.fabrica/",
    tags: ["Arts & Crafts Co-op", "Naomi Craft Hit", "Screen Printing", "Community Workshop", "Makerspace"],
    description: "An extraordinary non-profit community makerspace and cooperative art studio in SF. Dedicated to fostering accessible creative skills, they offer hands-on workshops in textiles, ceramics, printing, woodworking, and electronics for makers of all ages.",
    tips: "Check their online schedule for family-friendly weekend drop-in craft labs or community open-make evenings."
  },
  {
    id: "terra-mia-ceramic-studio",
    title: "Terra Mia Ceramic Studio Pottery Painting",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Noe Valley / 24th St, SF",
    address: "1314 Castro St, San Francisco, CA 94114",
    lat: 37.7513,
    lng: -122.4346,
    driveTime: "Local SF",
    duration: "2 hours",
    bestTime: "Weekend afternoon followed by a stroll down 24th Street",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi can pick her own ceramic figurine (kittens, dolphins, unicorns, or custom bowls) and paint it with vibrant glaze colors, glitter dots, and stencils!",
    arseniyHighlights: "A relaxing, creative date where Arseniy and Joanna can design a commemorative 32nd birthday coffee mug or custom souvenir platter.",
    arseniyFoodPick: "Walk down 24th St to Novy for grilled Greek lamb chops with lemon potatoes, or enjoy a velvety cappuccino and pastries at Martha & Bros.",
    joannaVeggiePick: "Stroll over to Noe Valley Bakery for fresh raspberry scones or enjoy vegetarian flatbreads and salads at Novy on 24th St.",
    instagramHandle: "@theres_a_food_for_that",
    instagramUrl: "https://www.instagram.com/theres_a_food_for_that/",
    tags: ["Pottery Painting", "Naomi Craft Hit", "Noe Valley", "Keepsake Maker", "Family Creative"],
    description: "A sunny, cheerful ceramic painting studio in the heart of Noe Valley. Pick your favorite bisque pottery piece from hundreds of shelves, choose your glaze palettes, and create permanent kiln-fired works of art to treasure forever.",
    tips: "Pieces are glazed and fired in the kiln, ready for pickup a few days later — a wonderful lasting souvenir of Arseniy's birthday celebration."
  },
  {
    id: "museum-craft-design-makeart",
    title: "Museum of Craft and Design (MCD) & MakeArt Lab",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Dogpatch / Historic Waterfront, SF",
    address: "2569 3rd St, San Francisco, CA 94107",
    lat: 37.7584,
    lng: -122.3884,
    driveTime: "Local SF",
    duration: "1.5 - 2 hours",
    bestTime: "Saturday afternoon during family MakeArt workshop hours",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi can dive into the dedicated 'MakeArt' laboratory with guided art prompts, free materials (wire, beads, fabrics, wood), and take-home craft projects!",
    arseniyHighlights: "Cutting-edge contemporary craft exhibitions exploring architecture, modern industrial design, metalwork, and sustainable textiles.",
    arseniyFoodPick: "Cross 3rd Street into Dogpatch to Magnolia Brewing for smoky brisket, double IPAs, sour beers, and mezcal old fashioneds.",
    joannaVeggiePick: "Walk two blocks down 3rd St to Piccino for seasonal wood-fired pizza with shaved fennel, Meyer lemon, and truffled pecorino.",
    instagramHandle: "@bigartloop",
    instagramUrl: "https://www.instagram.com/bigartloop/",
    tags: ["Craft Museum", "MakeArt Lab", "Naomi Craft Hit", "Dogpatch Arts", "Hands-on Art"],
    description: "The only museum in Northern California exclusively devoted to contemporary craft and design. Highlights innovation in handmade craft alongside a free, fully equipped hands-on MakeArt project studio where families build sculptures and textiles together.",
    tips: "MCD offers free admission days and provides MakeArt kits to go with every family visit."
  },
  {
    id: "scrap-sf-creative-reuse",
    title: "SCRAP SF Creative Reuse & Treasure Hunt",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80",
    category: "family",
    spreadsheetItem: false,
    neighborhood: "Bayview / Hunters Point, SF",
    address: "2150 Newcomb Ave, San Francisco, CA 94124",
    lat: 37.7371,
    lng: -122.3995,
    driveTime: "Local SF",
    duration: "1.5 hours",
    bestTime: "Thursday to Saturday afternoon",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi will feel like she's on a pirate treasure hunt digging through bins of sparkling vintage buttons, shiny beads, colorful fabric scraps, and rubber stamps!",
    arseniyHighlights: "The oldest creative reuse center in the nation: an inspiring wonderland of surplus architecture supplies, vintage maps, photography slides, and funky retro artifacts.",
    arseniyFoodPick: "Stop by Laughing Monk Brewing in Bayview for Belgian-style abbey ales, fruited kettle sours, and juicy double IPAs brewed on-site.",
    joannaVeggiePick: "Head to nearby Craftsman and Wolves or Cafe Envy for fresh vegetarian avocado toast, roasted vegetable soup, and seasonal fruit tarts.",
    instagramHandle: "@sequoia.fabrica",
    instagramUrl: "https://www.instagram.com/sequoia.fabrica/",
    tags: ["Creative Reuse", "Craft Treasure", "Naomi Craft Hit", "DIY Supplies", "Unique SF"],
    description: "A legendary San Francisco institution founded in 1976. This nonprofit creative reuse center breathes new life into clean materials diverted from landfills, offering thousands of bins of art supplies, paper, fabric, beads, and curiosities for DIY crafters.",
    tips: "Bring a reusable tote bag! You can fill up an entire box of craft treasures for Naomi for just a few dollars."
  },

  // --- CONFIGURATION 4: UNIQUE THINGS ONLY IN SF & BIG ART ---
  {
    id: "downtown-first-thursdays-rave",
    title: "Downtown First Thursdays (DFT) Street Pop-Up Rave",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80",
    category: "unique",
    spreadsheetItem: false,
    neighborhood: "2nd Street Corridor / Downtown SF",
    address: "2nd St between Market & Howard St, San Francisco, CA 94105",
    lat: 37.7888,
    lng: -122.4001,
    driveTime: "Local SF",
    duration: "2 - 3 hours",
    bestTime: "First Thursday of every month (5:00 PM - 10:00 PM)",
    sunsetSpot: false,
    naomiApproved: false,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Lively nighttime block party with loud outdoor music and dancing crowds; best suited for an Arseniy & Joanna date night!",
    arseniyHighlights: "Arseniy's Night Out: 45,000+ people taking over 2nd Street with massive outdoor DJ stages, heavy bass, neon laser lighting, breakdance battles, and pop-up alleyway disco clubs.",
    arseniyFoodPick: "Pre-rave fuel: smash burgers and craft draft double IPAs at local taprooms, or hit the mezcal pop-up bars on 2nd Street for spicy mezcal palomas.",
    joannaVeggiePick: "Dozens of local food truck vendors lining the streets with vegan bao buns, vegetarian street noodles, falafel pita wraps, and churro stands.",
    instagramHandle: "@secret_sanfrancisco",
    instagramUrl: "https://www.instagram.com/secret_sanfrancisco/",
    tags: ["Only in SF", "Pop-Up Rave", "Street Party", "Outdoor DJs", "Nightlife Vibe"],
    description: "San Francisco's electric free monthly outdoor street block party transforming 2nd Street into an exhilarating open-air festival. With multiple DJ dance stages, artisan night markets, neon art, disco alleys, and street performers.",
    tips: "Completely free entry! Take BART/Muni directly to Montgomery St station for zero parking hassle."
  },
  {
    id: "grace-light-cathedral",
    title: "Grace Light & Candlelight at Grace Cathedral",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80",
    category: "unique",
    spreadsheetItem: false,
    neighborhood: "Nob Hill, SF",
    address: "1100 California St, San Francisco, CA 94108",
    lat: 37.7919,
    lng: -122.4137,
    driveTime: "Local SF",
    duration: "1 - 1.5 hours",
    bestTime: "Evening ticketed sessions (check Grace Cathedral calendar for Grace Light dates)",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi can lie flat on the labyrinth floor with yoga mats and look up into a magical cone of light with ambient cosmic music.",
    arseniyHighlights: "Lying down directly on the indoor labyrinth under French Gothic cathedral arches while a 100-foot moving cylindrical sheet of light and spatial soundscapes wash over you.",
    arseniyFoodPick: "Walk over to Comstock Saloon or Pacific Cocktail Haven for an artisanal mezcal Oaxaca old fashioned, followed by steak frites and a double cortado.",
    joannaVeggiePick: "After the meditative light bath, walk down California St to Tonga Room for tropical mocktails and vegetarian stir fry, or hop over to Nob Hill Cafe for vegetarian risotto.",
    instagramHandle: "@secret_sanfrancisco",
    instagramUrl: "https://www.instagram.com/secret_sanfrancisco/",
    tags: ["Only in SF", "Grace Light", "Laser & Sound", "Cathedral Labyrinth", "Bucket List"],
    description: "A world-renowned immersive art installation created by light artist George Zisiadis and composer David Grenfell. Visitors lie on the labyrinth of the grand French Gothic cathedral as a monumental 100-foot curtain of laser light slowly descends through rising mist.",
    tips: "Tickets sell out quickly — book on Grace Cathedral's website in advance. Wear warm, cozy clothing and bring a pillow or blanket."
  },
  {
    id: "the-box-shop-big-art",
    title: "The Box Shop SF & Monumental Big Art Safari",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    category: "unique",
    spreadsheetItem: false,
    neighborhood: "Bayview / Hunters Point, SF",
    address: "951 Hudson Ave, San Francisco, CA 94124",
    lat: 37.7388,
    lng: -122.3789,
    driveTime: "Local SF",
    duration: "1.5 - 2 hours",
    bestTime: "Weekend afternoon or open house art tours",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: true,
    naomiNote: "Naomi can marvel at giant metal mechanical dinosaurs, kinetic fire flowers, and brightly painted shipping containers converted into artist studios!",
    arseniyHighlights: "The epicenter of San Francisco's monumental public and Burning Man art community: wander through acres of massive steel sculptures, mechanical creatures, and neon installations.",
    arseniyFoodPick: "Head to Barebottle Brewing nearby in Bernal/Bayview for wild sour beers, hazy double IPAs on tap, and food truck smash burgers.",
    joannaVeggiePick: "Stop by Radio Africa & Kitchen in Bayview for Ethiopian-inspired roasted eggplant, spiced lentils, and injera flatbreads.",
    instagramHandle: "@bigartloop",
    instagramUrl: "https://www.instagram.com/bigartloop/",
    tags: ["Big Art Loop", "Burning Man Art", "Metal Sculptures", "Only in SF", "Makers & Creatives"],
    description: "Founded by artist Charles Gadeken, The Box Shop is a collaborative community workspace and sanctuary for monumental kinetic art, industrial metal sculpture, and illuminated public installations. Walking through the yard feels like stepping onto an otherworldly planet of creativity.",
    tips: "Check the Big Art Loop and Box Shop social channels for tour times and open house events."
  },
  {
    id: "sf-city-hall-light-show",
    title: "San Francisco City Hall Architectural Laser Light Show",
    image: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80",
    category: "unique",
    spreadsheetItem: false,
    neighborhood: "Civic Center, SF",
    address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102",
    lat: 37.7793,
    lng: -122.4193,
    driveTime: "Local SF",
    duration: "45 minutes",
    bestTime: "Evening / Night (illuminations turn on at dusk daily)",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi will love seeing the colossal gold-leaf dome glowing in rotating colors (cyan, magenta, amber) and running across the illuminated Civic Center Plaza fountain.",
    arseniyHighlights: "Marvel at the world's fifth-largest dome (higher than the US Capitol) bathed in computer-controlled LED architectural projection mapping and lasers during festive evenings.",
    arseniyFoodPick: "Dinner in Hayes Valley at Rich Table or Monsieur Benjamin for prime dry-aged steak frites, grilled lamb, and mezcal craft cocktails.",
    joannaVeggiePick: "Stroll three blocks into Hayes Valley for dinner at Absinthe Brasserie or grab handmade vegetarian pasta at a Mano.",
    instagramHandle: "@secret_sanfrancisco",
    instagramUrl: "https://www.instagram.com/secret_sanfrancisco/",
    tags: ["Only in SF", "Laser Lights", "Civic Center", "Architectural Wonder", "Nighttime Glow"],
    description: "The crown jewel of American Beaux-Arts architecture. City Hall's majestic 307-foot dome is fitted with a computerized LED lighting system that projects custom multi-color light sequences and laser mapping celebrating SF history, arts, and civic holidays.",
    tips: "View the illumination from the center of Civic Center Plaza facing the grand west steps for the best symmetrical photos."
  },
  {
    id: "the-wave-organ-marina",
    title: "The Wave Organ & Marina Acoustic Stone Jetty",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    category: "unique",
    spreadsheetItem: false,
    neighborhood: "Marina District / St. Francis Spit, SF",
    address: "83 Marina Green Dr, San Francisco, CA 94123",
    lat: 37.8085,
    lng: -122.4402,
    driveTime: "Local SF",
    duration: "1 hour",
    bestTime: "HIGH TIDE at sunset (the acoustic pipes only play music when waves hit!)",
    sunsetSpot: true,
    naomiApproved: true,
    naomiAnimals: true,
    naomiCrafts: false,
    naomiNote: "Naomi can press her ears directly against the stone pipes to hear the ocean 'sing', spot harbor seals poking their heads above water, and explore the stone jetty!",
    arseniyHighlights: "Built with salvaged carved marble and granite from demolished historic cemeteries, this acoustic sculpture converts the rhythm of crashing waves into resonant, haunting organ notes.",
    arseniyFoodPick: "Head to Fort Masons Radhaus for Bavarian draft beers, braised pork shanks, and grilled sausages, or grab a rich cappuccino at Equator Coffee.",
    joannaVeggiePick: "Walk along the Marina Green to Radhaus in Fort Mason for Bavarian soft pretzels, warm obatzda cheese dip, and vegetarian spätzle with craft lagers.",
    instagramHandle: "@curious.connie",
    instagramUrl: "https://www.instagram.com/curious.connie/",
    tags: ["Only in SF", "Wave Organ", "Acoustic Art", "High Tide Sunset", "Harbor Seals"],
    description: "Created by Peter Richards and George Gonzales in 1986 on a jetty extending into the bay. Composed of 25 PVC and concrete acoustic pipes submerged at various depths, the movement of tidal waves forces air through the pipes, creating gentle, gurgling acoustic harmonies.",
    tips: "Crucial tip: Check the SF tide table before going! The organ is quiet at low tide and comes alive with deep hollow resonance during high tide."
  },
  {
    id: "church-of-8-wheels",
    title: "Church of 8 Wheels Roller Disco Sanctuary",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80",
    category: "unique",
    spreadsheetItem: false,
    neighborhood: "Fillmore / Western Addition, SF",
    address: "554 Fillmore St, San Francisco, CA 94117",
    lat: 37.7733,
    lng: -122.4308,
    driveTime: "Local SF",
    duration: "2 hours",
    bestTime: "Friday or Saturday evening (family sessions early evening, adult dance party later)",
    sunsetSpot: false,
    naomiApproved: true,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "Naomi can lace up retro quad roller skates, glide under shimmering disco balls, and high-five the Godfather of Skate!",
    arseniyHighlights: "Roller-skating inside a sacred 1898 Romanesque Catholic church beneath vaulted stained-glass windows, spinning disco lights, and funky bass lines.",
    arseniyFoodPick: "Post-skate drinks on Lower Haight at Toronado for legendary sour beers and Russian River IPAs, or artisan mezcal at Noc Noc.",
    joannaVeggiePick: "Grab a post-skate bite nearby on Lower Haight: vegan comfort food at VeganBurg or vegetarian wood-fired pizza at Berliner Baeren.",
    instagramHandle: "@secret_sanfrancisco",
    instagramUrl: "https://www.instagram.com/secret_sanfrancisco/",
    tags: ["Only in SF", "Roller Disco", "Historic Church", "Funk & Soul", "Pure Joy"],
    description: "An authentic, joy-filled SF institution. Housed within the historic former Sacred Heart Church, David Miles Jr. ('The Godfather of Skate') has created an exuberant roller-disco wonderland where stained-glass saints overlook grooving skaters bathed in neon disco lights.",
    tips: "Skate rentals and safety gear are available on site. All skill levels from beginner waddlers to dance pros are welcomed with open arms."
  },
  {
    id: "audium-sound-theater",
    title: "Audium: Theater of Sound-Sculptured Space",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80",
    category: "unique",
    spreadsheetItem: false,
    neighborhood: "Bush St / Pacific Heights, SF",
    address: "1616 Bush St, San Francisco, CA 94109",
    lat: 37.7884,
    lng: -122.4243,
    driveTime: "Local SF",
    duration: "1.5 hours",
    bestTime: "Thursday, Friday, or Saturday evening 7:30 PM",
    sunsetSpot: false,
    naomiApproved: false,
    naomiAnimals: false,
    naomiCrafts: false,
    naomiNote: "The performance is held in 100% total darkness; recommended as a private date night experience for Arseniy and Joanna!",
    arseniyHighlights: "Sitting in complete, pitch-black darkness as sound sculptures sweep through 176 speakers overhead, beneath your seat, and circling the walls in total spatial movement.",
    arseniyFoodPick: "Intimate late-night dinner at Wildseed or Harper & Rye for single-estate tequila and mezcal cocktails, or a prime steak dinner on Polk Street.",
    joannaVeggiePick: "Head to nearby Polk Street for dinner at Wildseed (100% plant-based restaurant featuring spicy mushroom pizzas, mezze platters, and craft cocktails).",
    instagramHandle: "@curious.connie",
    instagramUrl: "https://www.instagram.com/curious.connie/",
    tags: ["Only in SF", "Pitch Darkness", "176 Speakers", "Spatial Sound", "Mind Expanding"],
    description: "The only theater in the world purpose-built for spatialized sound concerts. Founded in the 1960s by Stan Shaff and Doug McEachern, Audium immerses listeners in an acoustic maze of 176 custom speakers in absolute, pitch-black darkness.",
    tips: "Arrive on time — late seating is strictly not permitted once the blackout performance begins."
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ADVENTURES_DATA };
}
